"""Isotropic RCWA toolkit."""
from .geometry import (
    Pattern2D,
    analyticCircularPostLayer,
    annularPostLayer,
    circularPostLayer,
    crossPostLayer,
    ellipticalPostLayer,
    homogeneousLayer,
    photonicCrystalSlab,
    polygonPostLayer,
    rectangularHollowPostLayer,
    rectangularPostLayer,
    stack,
)
from .materials import AIR, SI1550, SIO2, VACUUM, IsotropicMaterial, constantEpsilon, constantIndex
from .solver import (
    CompiledLayer,
    DiffractionOrder,
    Layer,
    LayerEigTiming,
    LayerFieldSolution,
    RCWAResult,
    StackTiming,
)
from .analytic import AnalyticAnnulus, AnalyticDisk, AnalyticEllipse, AnalyticRectangle
from .backend import ArrayBackend, resolveBackend
from .builder import LayerStack, PatternLayer
from .convergence import OrderSweepPoint, OrderSweepReport, sweepOrders
from .fields import (
    fieldComponentsXy,
    fieldComponentsXz,
    fieldSliceXy,
    fieldSliceXz,
    homogeneousFourierFields,
    incidentFieldIntensities,
    layerFourierFields,
    reconstructFourierGrid,
    reconstructFourierXy,
    stackFieldComponentsXy,
    stackFieldComponentsXz,
    stackFieldSliceXy,
    stackFieldSliceXz,
)
from .simulation import LayerSpec, RCWASimulation
from .varrcwa import AdaptiveLayerSpec, adaptiveZStack

__all__ = [
    "AIR",
    "AnalyticAnnulus",
    "AnalyticDisk",
    "AnalyticEllipse",
    "AnalyticRectangle",
    "ArrayBackend",
    "CompiledLayer",
    "DiffractionOrder",
    "IsotropicMaterial",
    "Layer",
    "LayerEigTiming",
    "LayerFieldSolution",
    "LayerStack",
    "LayerSpec",
    "Pattern2D",
    "PatternLayer",
    "RCWASimulation",
    "RCWAResult",
    "StackTiming",
    "OrderSweepPoint",
    "OrderSweepReport",
    "SI1550",
    "SIO2",
    "VACUUM",
    "analyticCircularPostLayer",
    "annularPostLayer",
    "circularPostLayer",
    "constantEpsilon",
    "constantIndex",
    "crossPostLayer",
    "ellipticalPostLayer",
    "fieldSliceXy",
    "fieldSliceXz",
    "fieldComponentsXy",
    "fieldComponentsXz",
    "homogeneousFourierFields",
    "incidentFieldIntensities",
    "homogeneousLayer",
    "layerFourierFields",
    "photonicCrystalSlab",
    "polygonPostLayer",
    "rectangularHollowPostLayer",
    "rectangularPostLayer",
    "resolveBackend",
    "reconstructFourierGrid",
    "reconstructFourierXy",
    "stackFieldComponentsXy",
    "stackFieldComponentsXz",
    "stackFieldSliceXy",
    "stackFieldSliceXz",
    "stack",
    "sweepOrders",
    "AdaptiveLayerSpec",
    "adaptiveZStack",
]
